### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by mlsokolova** [MoneyBagCoin/MoneyBagCoin#2]
Hi
Could you write requirements for building and running MoneyBagCoin 1.1.0 on Linux please. 
What libraries and with what versions should be downloaded and compiled before running of MoneyBagCoin.

**Comment by MoneyBagCoin** [comment]
Ok! We are going to prepare it, it will be available in 1-2 days

**Comment by MoneyBagCoin** [comment]
Solved, added it in our wiki 
https://github.com/MoneyBagCoin/MoneyBagCoin/wiki/Linux-Install
